### ISSUE TITLE
Chinese, Japanese, Korean and Punjabi character are not visible

### ISSUE THREAD

**Issue by johanmazel** [citp/OpenWPM#100]
Chinese, Japanese, Korean and Punjabi characters inside websites are not correctly displayed.
This is a problem for screenshot taking.

Here are some examples:
Chinese: https://www.hao123.com/
Japanese: http://www.yahoo.co.jp/
Korean: http://www.chosun.com/
Pundjabi: https://www.google.co.in/

I tried to setup chinese with the associated extension (zn-CH.xpi) in this directory (https://ftp.mozilla.org/pub/firefox/releases/45.0/linux-x86_64/xpi/) but it did not work.

**Comment by johanmazel** [comment]
I actually did not have the fonts installed on the machine.
Sorry for the noise.

**Comment by dreisman** [comment]
No problem!
