### ISSUE TITLE
Limiting screenshots to the visible window

### ISSUE THREAD

**Issue by hadiasghari** [citp/OpenWPM#113]
The method `CommandSequenec.save_screenshot()` currently saves a screen shot of the FULL HTML page. This is not always desirable, and a parameter to limit the screenshot to the visible window is welcome. 

The following screenshot from YouTube illustrates the point:
 
![gb2_youtube_com](https://cloud.githubusercontent.com/assets/5025042/20893994/d2d31696-bae1-11e6-9a83-560442f229da.png)

Two reasons for the parameter:

- For purposes such as identifying cookie-notices, only the visible browser window matters, and the difference in disk-use can be significant.
- Additionally, the full page rendering can cause Selenium timeouts, with frequent errors: "TaskManager ... Timeout while executing command, SAVE_SCREENSHOT, killing browser manager"

**Comment by englehardt** [comment]
Viewport-only screenshots are now the default in Selenium 3, which we moved to in #152. Thus `CommandSequence::save_screenshot` will only save the visible portion of the current page.

#156 adds a separate command for full page screenshots.
