### ISSUE TITLE
Remove `create_javascript_calls_table.sql`

### ISSUE THREAD

**Issue by gunesacar** [citp/OpenWPM#130]
Is there a reason to keep [`create_javascript_calls_table.sql`](https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/data/create_javascript_calls_table.sql) in the repo?

I can't seem to find any reference to it.

**Comment by englehardt** [comment]
This was left over from fourthparty and is unused. Removed in 4431c4c73a72b879c7ca12de40fded38f4847ca9
