### ISSUE TITLE
other extension

### ISSUE THREAD

**Issue by Helpper** [citp/OpenWPM#141]
How can I add a new extension such as userAgent Switcher?

**Comment by englehardt** [comment]
Extensions can be added during browser initialization through the `FirefoxProfile` selenium class, the interface is described [here](https://seleniumhq.github.io/selenium/docs/api/dotnet/html/T_OpenQA_Selenium_Firefox_FirefoxProfile.htm) (note these are java docs so the syntax is slightly different).

You must add a custom extension [after the profile is created](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/DeployBrowsers/deploy_firefox.py#L23), but [before the browser is launched](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/DeployBrowsers/deploy_firefox.py#L130). 

For an example, check out how we [add https everywhere](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/DeployBrowsers/configure_firefox.py#L46-L52). Here we both add the extension and set a few `about:config` variables for it.

Also note that it isn't necessary to use an extension to switch the browser's user agent. You can do so simply by setting an `about:config` preference in the browser's profile, as we do [here](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/DeployBrowsers/deploy_firefox.py#L65). Even when the browsers user agent is changed there are still many ways to interrogate information about the browser as discussed in #17.

**Comment by Helpper** [comment]
Thank you for your detailed explanation!

**Comment by Helpper** [comment]
Thank you for your explanation!
