### ISSUE TITLE
ip_address in domain utils identifies hostnames of 16 bytes as ipv6 addresses

### ISSUE THREAD

**Issue by dreisman** [citp/OpenWPM#146]
In domain_utils.py, if the hostname found in get_public_suffix_plus_one() is exactly 16 bytes, it will get inappropriately identified as an ipv6 address. This may not be an issue now, but the bug could be triggered in very subtle ways.

We could disregard ipv6 addresses for now, since they never seem to occur NOW, but I think that would be a pretty hacky change.

**Comment by dreisman** [comment]
RFC 2732 says that using ipv6 as a valid domain requires that you put square brackets around the bytes. Browsers seem to use that logic.

We could require square brackets when checking for ipv6 in get_public_suffix_plus_one

**Comment by englehardt** [comment]
@dreisman and I found this bug in a different implementation of `domain_utils.py`, but I don't think it's present in the version in this repository. In that version, hostnames were passed as python 2 byte strings (`str` type). When that happens the the `ipaddress` library assumes that the hostname must be a "packed address" and tries to unpack it (provided it's the correct length, either 4 or 16 bytes). See the relevant code [here](https://github.com/phihag/ipaddress/blob/4233f21f1b461899820626d493a8ad031d0e6fc7/ipaddress.py#L1396-L1402), where `_compat_bytes_to_byte_vals` is defined [here](https://github.com/phihag/ipaddress/blob/4233f21f1b461899820626d493a8ad031d0e6fc7/ipaddress.py#L34-L35) for python 2.

In this version of `domain_utils.py` we pass hostnames as unicode, so they will never be interpreted as packed byte strings.
