### ISSUE TITLE
Firefox binary path hard coded

### ISSUE THREAD

**Issue by randomwalker** [citp/OpenWPM#16]
The path to the binary is 

./firefox/firefox

(in deploy_firefox.py:170)

Is the assumption that the user has a custom firefox install inside the OpenWPM directory? We don't seem to mention this in the tutorial. The demo fails out of the box for this reason (probably what's causing the error in #15 ).

**Comment by englehardt** [comment]
This should be created by `install.sh`. We now use a specific version of Firefox and selenium that I've found to work well together. I've updated the wiki instructions. Let me know if you still have issues after running that script.
