### ISSUE TITLE
Replace SQL with a generic data format that supports multiple output formats

### ISSUE THREAD

**Issue by englehardt** [citp/OpenWPM#163]
It would be nice to have some flexibility in the output format of the data collected by the built-in commands and instrumentation. Currently, all of the instrumentation probes build SQL statements directly and submit them to the [SQLite Aggregator](https://github.com/citp/OpenWPM/blob/2fe06ab3d7aee48f36ff266928b36d3a245a1f06/automation/DataAggregator/DataAggregator.py) process. Instead, we could use some output-format-agnostic structure internally, and pass those records to the proper module for saving depending on the configuration. 

The extension already does this to [some extent](https://github.com/citp/OpenWPM/blob/2fe06ab3d7aee48f36ff266928b36d3a245a1f06/automation/Extension/firefox/lib/loggingdb.js#L194-L221), but most of the python code builds queries directly.

**Comment by dijksterhuis** [comment]
Are you essentially looking for a utility to dynamically handle SQL statement building for the Python code sections? Something like [this](https://github.com/dijksterhuis/useful-python/blob/master/SQLStatement.py)?

**Comment by englehardt** [comment]
> Are you essentially looking for a utility to dynamically handle SQL statement building for the Python code sections?

It's not exactly what we're looking for, but it could be helpful. We'd like to be able to save data from the instrumentation in different formats (i.e., have the option to save to something other than a sqlite database). Other SQL databases would be a good start, but I could also imagine serializing all of the site data to a json file.

A possible approach would be to replace all of the inline SQL statements in the python code with dictionaries, which can then be serialized and passed to the aggregator process. That process could use a "SQLiteWriter" based on your utility to build and submit queries to a sqlite database from the dictionaries. In the future, we could add additional "Writer" classes to support other formats.
