### ISSUE TITLE
Can't get to the point where i can use OpenWPM at simplest tests

### ISSUE THREAD

**Issue by GavGav111** [citp/OpenWPM#168]
Hi, all. I wasted too many time to start using OpenWPM, so right now its better to create new issue. Hoping for the help. Very tired of stacking here and there.

I've downloaded OpenWPM image and used it in my VirtualBox 5.1.0
I tried going 2 ways. 1st way is using OpenWPM files that goes inside image, 2nd is to delete original files and download latest. 

1st way:
simpliest test(almost with no changes in demo.py) goes well to the end ... but ... there is 'javascript' table is i add [js_instrument] option
2nd way:
give much more errors. first is : 
```
from multiprocess import Process, Queue
ImportError: No module named multiprocess
```
if i install `sudo pip install multiprocess` - then next error appears - 
```
from miniamf import sol
ImportError: No module named miniamf
```

I wasnt able win last error, even after installing 'sol' module for python. 
Pls help

**Comment by englehardt** [comment]
Hello, happy to help!

Using the virtual image is not advised. It's several years out of date and based on a version of Ubuntu which is no longer supported. I've removed those instructions from the wiki.

Instead, you should install OpenWPM on Ubuntu 16.04+ by cloning the repository and running the [install script](https://github.com/citp/OpenWPM/blob/master/install.sh). You can do this on a virtual machine you've set up, on a cloud machine (like Amazon's EC2 service), or on a local machine.

Let us know if you run into any more issues.

**Comment by GavGav111** [comment]
Thank you
