### ISSUE TITLE
question: how to get an url and browse then to few sub pages

### ISSUE THREAD

**Issue by rriemann** [citp/OpenWPM#170]
Hello,

I want to get to one url, store cookies and screenshots, and check out then i.e. 1 sub pages.

However, when I run

- `command_sequence.get(sleep=0, timeout=60)`
- `command_sequence.browse(num_links=1, sleep=1, timeout=60)`

, I get two times the same page.

So how can I prevent crawling (and storing http_requests/responses) two times the same page?

Thank you!
Robert

**Comment by englehardt** [comment]
Unfortunately there isn't an easy way to do this. The best approach will be to [add a new command](https://github.com/citp/OpenWPM/wiki/Platform-Demo#adding-a-new-command) in place of `browse` that doesn't request the initial page. Something like `command_sequence.visit_internal_link`, which parses the page for internal links and clicks one.
