### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by firestar1** [citp/OpenWPM#18]
Dear,
I had checked your source code but still not clear if how to make two browsers execute a command at the same time (for example, every 1 hour, they should query data from website). Could you give me some ideas?
Thank you

**Comment by englehardt** [comment]
You should take a look at `demo.py`. That shows how to execute three browsers at the same time. You'll only see two on screen, as the other one is [started in headless mode](https://github.com/citp/OpenWPM/blob/master/demo.py#L22). If you want to schedule jobs to run once per hour, it's best to write a python script like `demo.py`, which visits a site and set up a [cron job](https://help.ubuntu.com/community/CronHowto) to run that script once per hour.
