### ISSUE TITLE
Two errors while crawling (no crash)

### ISSUE THREAD

**Issue by Alive-and-Well** [citp/OpenWPM#180]
Hi,
I am just starting to use open WPM. 
During a crawl run I get two error messages numerous times. The URL in the error messages is always different:

1. ERROR    - Error while retrieving additional channel information for URL: 
https://s.uicdn.com/uimag/1/assets-static/webfonts/Fira/FiraSans-Bold_160512.woff
Error text:{} 

2. Redirect from channel {e9218aeb-1f09-4e82-b4af-2b3b06350d20} loading URL https://ad11.adfarm1.adition.com/tagging?type=image&network=42&tag[yieldlab.yladmag]=224398,0,263799&tag[yieldlab.ylpmag]=551 to channel {c5f747ee-772f-416f-9f70-c66b745bb276} loading URL https://imagesrv.adition.com/1x1.gif

The crawler does not crash and eventually terminates but I am still not happy about these errors. What do these error messages mean? And how can I fix them?

**Comment by englehardt** [comment]
Error 1 is the result of what I described in #184. These errors just mean that we were unable to classify whether or not a channel was third-party channel. They won't effect the crawl or the data that's logged.

Error 2 is the result of an unnecessary debug print statement. I've removed it in https://github.com/citp/OpenWPM/commit/7ee14e3bff2d14ec4f41aab9a6530908b8745d74.

Thanks!

**Comment by turban1988** [comment]
Thanks for the fix!
