### ISSUE TITLE
running simple analysis demo

### ISSUE THREAD

**Issue by sali123** [citp/OpenWPM#183]
when i run the simple analysis demo, an empty list will be printed. is this correct?

**Comment by englehardt** [comment]
Are you running `demo.py` or something else? Would you mind pasting the output you see?

**Comment by englehardt** [comment]
You're referring to https://github.com/citp/OpenWPM/wiki/Platform-Demo#running-a-simple-analysis right? That section was just meant as an example of how you could run an analysis on the dataset. It is not meant to be run on the output of `demo.py`. The idea people that if you ran a crawl which logged into several sites you could search for leaked email addresses in the dataset using those commands.

For the sites included in `demo.py` an empty list is the expected output.
