### ISSUE TITLE
Install OpenWPM as Firefox Extension

### ISSUE THREAD

**Issue by sali123** [citp/OpenWPM#191]
Is it possible to install OpenWMP instrumentation as firefox Extension so we can capture http traffic, profile cookies, javascript, javascript cookies, etc... as we navigate through any website on the internet. if yes, how to generate a compatible version to firefox v60.

**Comment by englehardt** [comment]
See #148. As far as I can tell the upgrade to ESR 60 will be relatively easy since bootstrap extensions are still supported.
