### ISSUE TITLE
Add support for issuing a sequence of commands to a single browser.

### ISSUE THREAD

**Issue by englehardt** [citp/OpenWPM#27]
When crawling with multiple browsers, it is currently more difficult then it should be to issue multiple commands to the same browser instance. For example, consider the scenario where would are running a measurement with two crawlers, `browser_1` and `browser_2`, and you want to issue a `get`, `parse`, and `dump` command. If you write:
```
for site in sites:
    TaskManager.get(site)
    TaskManager.parse()
    TaskManager.dump()
```
`browser_1` will issue a `get`, `browser_2` will issue a `parse`, and the one that finishes first will issue `dump`. It's possible to avoid this by explicitly issuing the commands with an index, so:
```
TaskManager.get(site, index=1)
TaskManager.parse(index = 1)
TaskManager.dump(index = 1)
TaskManager.get(site, index=2)
TaskManager.parse(index = 2)
TaskManager.dump(index = 2)
```
but this is less than ideal since it will serialize your program. Of course it's possible to avoid serialization by checking if the browser is available before issuing the command and using some system to queue to commands in the crawl script.

This should be supported by the infrastructure. The simplest solution is just to queue the commands in the TaskManager per browser, so a user could issue commands by index without serializing their program. However, for very large crawls these queues may grow to take up a large amount of memory.

Instead, I think it makes sense to introduce a notion of a command sequence. The user can initialize an instance of a `CommandSequence` object, add the respective commands to it, and ask the `TaskManager` to execute the `CommandSequence` on the first available browser. This would look something like:
```
for site in sites:
    command_sequence = CommandSequence()
    command_sequence.get(site)
    command_sequence.parse()
    command_sequence.dump()

    TaskManager.execute(command_sequence)
```

**Comment by vtoubiana** [comment]
That'd be great. A work around is to specify the browser_index (as suggested) and to use python's pool to avoid serialization.
This is not ideal though as Pool parallelization is not optimal.
