### ISSUE TITLE
Virtual Machine OpenWPM-0.1.1.ova password

### ISSUE THREAD

**Issue by masdeeper** [citp/OpenWPM#3]
I need root access to the virtual machine OpenWPM-0.1.1.ova to install  softwares. I searched the documentation but I did not find the password.

Thanks :)

****************
EDIT 1
The pasword for the OpenWPM user is "password" and this user is in the sudoer group. 
****************

**Comment by englehardt** [comment]
Yes, you figured it out. Sorry for the delay in getting back to you. I'll add this to the documentation. Thanks!
