### ISSUE TITLE
moz_cookies table is always empty

### ISSUE THREAD

**Issue by thepurriah** [citp/OpenWPM#56]
About a week ago I tried the new updates on master branch. It seems to me that moz_cookies table is always empty when get/browser and dump_profile_cookie commands are being run sequentially. It used to work before. Is there any explanation for it?

**Comment by englehardt** [comment]
Did you close this issue because you found that the error was not in OpenWPM?

**Comment by thepurriah** [comment]
Yes. It was a configuration problem.

**Comment by AnotherKamila** [comment]
What configuration problem? I am struggling with the same thing. How do I enable persistent cookie storage?
