### ISSUE TITLE
Update wiki documentation to reflect new use of CommandSequences

### ISSUE THREAD

**Issue by dreisman** [citp/OpenWPM#75]
The wiki will be out of date once CommandSequences are merged into master, so the documentation should be improved. #74

**Comment by englehardt** [comment]
Partially addressed in c85e769, but more is needed. In particular the [TaskManager](https://github.com/citp/OpenWPM/wiki/Task-Manager) page.

**Comment by englehardt** [comment]
I've refactored the wiki and removed the TaskManager page. Although the [Platform Architecture](https://github.com/citp/OpenWPM/wiki/Platform-Architecture) page needs to be updated these changes aren't specific to `CommandSequence`.
