### ISSUE TITLE
Missing requirements in install script for debian

### ISSUE THREAD

**Issue by malexmave** [citp/OpenWPM#87]
Currently installing OpenWPM in a debian VM, and at least there, the install script is missing a few required libraries. They are (using the latest tagged release):

    sudo apt-get install libssl-dev libboost-python-dev libleveldb-dev libffi-dev python-dev build-essential python2.7 xvfb

Without these packages, the python modules installed via pip will not compile and the demo script will not run. I don't know if this is an artifact of the fact that I am using debian, not Ubuntu, but this may be helpful for others.

Additionally (and this is probably an artifact of debian), the firefox installation fails, and I have yet get the demo script to work with the downloaded firefox from `firefox-bin`. But I'm still working on that part.

**Comment by englehardt** [comment]
Are you using `install.sh`? All of these system requirements (with the exception of python2.7) are included in that install script, See: https://github.com/citp/OpenWPM/blob/master/install.sh#L20

I'm guessing python2.7 is removed from the latest Debian release? Looks like it's being slowly removed from Ubuntu as well: https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#Updated_Packages.

**Comment by malexmave** [comment]
Huh. I was using `install.sh`, in the version from the latest tagged release, which appearently *does* include these. For some reason, they weren't installed when I ran the script and I had to install them manually. This confuses the hell out of me, but probably means that the problem is on my end, not yours. Closing this issue, sorry for the confusion.
