### ISSUE TITLE
Audio Fingerprint test is still flaky

### ISSUE THREAD

**Issue by dreisman** [citp/OpenWPM#96]
The test for audiocontext fingerprint instrumentation (in test_extension.py) is still flaky — it's reliable on local machines, but travis seems to have some issue with it. This needs investigation.

**Comment by dreisman** [comment]
In branch "content," I've disabled the test for now when it's run on travis.

**Comment by englehardt** [comment]
I think this is safe to keep disabled. We've observed the bug in other branches as well.
